name: Build & Release
on:
  workflow_dispatch:
  push:
    paths:
      - "VERSION"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: pre-commit check
        run: |
          pip install pre-commit
          if ! pre-commit run --all-files --show-diff-on-failure
          then
            echo ''
            echo '=== Code style issue detected! ==='
            echo 'Suggest changes are listed above.'
            echo 'Please install pre-commit and run `pre-commit run --all-files` to fix it.'
            echo 'Strongly recommended to run `pre-commit install` to catch issues before pushing.'
            echo 'You can learn more abour pre-commit from https://pre-commit.com/'
            exit 1
          fi
      - name: Generate environmental variables
        run: |
          VERSION=$(cat VERSION)
          echo "tag_name=${VERSION}" >> $GITHUB_ENV
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf
      - name: Build packages
        run: |
          make deb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: false
          files: |
            src/packages/arm64/**/*.deb
            pkg.conf
      - name: Update Test repos
        uses: radxa-repo/update-repo-action@main
        with:
          test-repo: true
          token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
