name: Build & Release
on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Generate environmental variables
        run: |
          VERSION=$(cat VERSION)
          echo "tag_name=${VERSION}" >> $GITHUB_ENV
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf
      - name: Build packages
        run: |
          make deb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: false
          files: |
            debian/packages/arm64/**/*.deb
            pkg.conf
